version: 2

# 指定构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# 配置使用 sphinx 构建
sphinx:
    configuration: docs/conf.py

# 指定依赖文件路径
python:
  install:
    - requirements: docs/requirements.txt